#!/bin/bash

#Check if folder already exists
if [ ! -d ~/advancedGit ]; then
	#Make the folder
	mkdir ~/advancedGit
	echo "Making folder in home directory"
else
	echo "Folder already exists"
fi

#Deletes previous files created
if [ -f ~/advancedGit/file1.txt ]; then
	rm ~/advancedGit/*.txt
fi

#initialise counter
counter=1

#While loop used to recursively create folders until the specified amount is made
while [ $counter -le $1 ]
do
	echo "Creating file #" $counter
	touch ~/advancedGit/file$counter.txt
	echo "This is file" $counter", it's name is file"$counter".txt" > ~/advancedGit/file$counter.txt
	((counter++))
done

echo All done
