#!/bin/bash


if [ ! -d "teams" ]
then
cd
mkdir teams
cd teams
mkdir folders
cd folders
fi



if [ $1 ]
then
 
	if [ ! -d $1 ]
	then
		echo "Directory already exists"
	else
		mkdir $1
		cd $1

		if [ $2 ]
		then 
			
			echo "Matthew admits he was wrong about pizza give us bonus points" > $2.txt
		else
			echo "Please enter a file name"
		fi
	fi
else
	echo "File directory not enterd"
fi

